<a href="https://colab.research.google.com/github/Richish/hands_on_ml/blob/master/12_custom_models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
import numpy as np
import keras

In [ ]:
t=tf.constant([[1,2,3],[4,5,6.]])
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [ ]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [ ]:
t.shape, t.dtype

(TensorShape([2, 3]), tf.float32)

In [ ]:
t[:,1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [ ]:
t[...,1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [ ]:
t+10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [ ]:
tf.subtract(t,10)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-9., -8., -7.],
       [-6., -5., -4.]], dtype=float32)>

In [ ]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [ ]:
t@tf.transpose(t) # @ is for matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [ ]:
tf.matmul(t, tf.transpose(t))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [ ]:
tf.squeeze(t)# removes 1 dimensional elements

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [ ]:
tf.tile(t, [5,10]) # tiles the input t, along 0th axis- 5 times; and along 1st axis - 10 times

<tf.Tensor: shape=(10, 30), dtype=float32, numpy=
array([[1., 2., 3., 1., 2., 3., 1., 2., 3., 1., 2., 3., 1., 2., 3., 1.,
        2., 3., 1., 2., 3., 1., 2., 3., 1., 2., 3., 1., 2., 3.],
       [4., 5., 6., 4., 5., 6., 4., 5., 6., 4., 5., 6., 4., 5., 6., 4.,
        5., 6., 4., 5., 6., 4., 5., 6., 4., 5., 6., 4., 5., 6.],
       [1., 2., 3., 1., 2., 3., 1., 2., 3., 1., 2., 3., 1., 2., 3., 1.,
        2., 3., 1., 2., 3., 1., 2., 3., 1., 2., 3., 1., 2., 3.],
       [4., 5., 6., 4., 5., 6., 4., 5., 6., 4., 5., 6., 4., 5., 6., 4.,
        5., 6., 4., 5., 6., 4., 5., 6., 4., 5., 6., 4., 5., 6.],
       [1., 2., 3., 1., 2., 3., 1., 2., 3., 1., 2., 3., 1., 2., 3., 1.,
        2., 3., 1., 2., 3., 1., 2., 3., 1., 2., 3., 1., 2., 3.],
       [4., 5., 6., 4., 5., 6., 4., 5., 6., 4., 5., 6., 4., 5., 6., 4.,
        5., 6., 4., 5., 6., 4., 5., 6., 4., 5., 6., 4., 5., 6.],
       [1., 2., 3., 1., 2., 3., 1., 2., 3., 1., 2., 3., 1., 2., 3., 1.,
        2., 3., 1., 2., 3., 1., 2., 3., 1., 2., 3., 1., 

In [ ]:
tf.reduce_mean(t)

<tf.Tensor: shape=(), dtype=float32, numpy=3.5>

In [ ]:
tf.reduce_mean(t, axis=0)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2.5, 3.5, 4.5], dtype=float32)>

In [ ]:
tf.reduce_sum(t, axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 6., 15.], dtype=float32)>

## Tensors and NumPy
Tensors play nice with NumPy: you can create a tensor from a NumPy array, and vice
versa, and you can even apply TensorFlow operations to NumPy arrays and NumPy
operations to tensors:

In [ ]:
a=np.array([1,2,3.])
a

array([1., 2., 3.])

In [ ]:
t=tf.constant(a)
t

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

In [ ]:
tf.cast(t, dtype="float32") # numpy by default uses float64 so to optimize it is good to cast to float32. tf uses float32 by default anyways

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [ ]:
t.numpy()

array([1., 2., 3.])

In [ ]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 4., 9.])>

In [ ]:
np.square(t)

array([1., 4., 9.])

## Type conversions
Type conversions can significantly hurt performance, and they can easily go unnoticed
when they are done automatically. To avoid this, TensorFlow does not perform
any type conversions automatically: it just raises an exception if you try to execute an
operation on tensors with incompatible types. For example, you cannot add a float
tensor and an integer tensor, and you cannot even add a 32-bit float and a 64-bit float:

In [ ]:
tf.constant(40)+tf.constant(40.5)

In [ ]:
tf.constant(40.0)+tf.constant(40.0, dtype="float64")

In [ ]:
t2 = tf.constant(40., dtype=tf.float64)
tf.constant(2.0) + tf.cast(t2, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

## Variables
The constants cannot be modified. So we need variables, sisncei n neural networks these would be weights that will be changed during training

In [ ]:
v=tf.Variable([[1,2,3],[4,5,6.0]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

it can also be modified in place using the assign() method (or assign_add() or
assign_sub() which increment or decrement the variable by the given value). You
can also modify individual cells (or slices), using the cell’s (or slice’s) assign()
method (direct item assignment will not work), or using the scatter_update() or
scatter_nd_update() methods:

In [ ]:
v[1,2].assign(0) # assignment by slicing
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 0.]], dtype=float32)>

In [ ]:
v.assign(2*v) # cellwise operation

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10.,  0.]], dtype=float32)>

In [ ]:
v[:,2].assign([0,1])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  0.],
       [ 8., 10.,  1.]], dtype=float32)>

In practice you will rarely have to create variables manually, since Keras provides an add_weight() method that will take care of it for
you, as we will see. Moreover, model parameters will generally be
updated directly by the optimizers, so you will rarely need to
update variables manually.

tf.cast()

# Customizing Models and Training Algorithms
## Custom costs

In [ ]:
def huber_fn(y_true, y_pred):
    error = y_true - y_pred
    is_small_error = tf.abs(error) < 1
    squared_loss = tf.square(error) / 2
    linear_loss = tf.abs(error) - 0.5
    return tf.where(is_small_error, squared_loss, linear_loss)



In [ ]:
model.compile(loss=huber_fn, optimizer="nadam")
model.fit(X_train, y_train, [...])

## Saving and loading models that contain custom components

Keras just
saves the name of the function. However, whenever you load it, you need to provide a
dictionary that maps the function name to the actual function. More generally, when
you load a model containing custom objects, you need to map the names to the
objects:

In [ ]:
model = keras.models.load_model("my_model_with_a_custom_loss.h5", custom_objects={"huber_fn": huber_fn})

In [ ]:
# if you want to have custom threshold:
def create_huber(threshold=0.1):
    def huber_fn(y_true, y_pred):
        error = y_true - y_pred
        is_small_error = tf.abs(error) < threshold
        squared_loss = tf.square(error)
        linear_loss = tf.abs(error)
        return tf.where(is_small_error, squared_loss, linear_loss)
    return huber_fn

model.compile(loss=create_huber(2.0), optimizer="nadam")

model.load_model(model("my_model_with_a_custom_loss_threshold_2.h5", custom_objects={"huber_fn": create_huber(2.0)}))
# note that what gets saved is the name of the function we gave keras(huber_fn) and not the name of the function that we called(create_huber).
# But while loading, we need to map this name to the actual function that we will be calling. Also the threshold value is not saved and needs to be provided when loading

In [6]:
# The problenm of threshold not getting stored by creating HuberLoss as subclass of keras.losses.Loss and implementing it's get_config function
class HuberLoss(keras.losses.Loss):
     
    def __init__(self, threshold=1.0, **kwargs):
         self.threshold = threshold
         super().__init__(**kwargs)
    
    def call(y_true, y_pred):
        error = y_true - y_pred
        is_small_error = tf.abs(error) < self.threshold
        squared_loss = tf.square(error)
        linear_loss = tf.abs(error)
        return tf.where(is_small_error, squared_loss, linear_loss)

    def get_config():
        base_config = super().get_config()
        return {**base_config, "threshold": self.threshold }

model.compile(loss=HuberLoss(2.), optimizer="nadam") # threshold is also saved now
model = keras.models.load_model("my_model_with_a_custom_loss_class.h5", custom_objects={"HuberLoss": HuberLoss}) # no need to provide threshold here

"""
When you save a model, Keras calls the loss instance’s get_config() method and
saves the config as JSON in the HDF5 file. When you load the model, it calls the
from_config() class method on the HuberLoss class: this method is implemented by
the base class (Loss) and just creates an instance of the class, passing **config to the
constructor.
"""

## Custom Activation Functions, Initializers, Regularizers, and Constraints
Custom activation
functions, initializers, regularizers, and constraints. can be defined in same way as custom loss above.


In [7]:
def my_softplus(z): # (log(e**z+1))
    return tf.math.log(tf.exp(z)+1.0)

def my_glorot_initializer(shape, dtype=tf.float32):
    stddev = tf.sqrt(2.0/(shape[0]+shape[1]))
    return tf.random.normal(shape, mean=0.0, stddev=stddev)

def my_l1_regularizer(weights):
    return tf.reduce_sum(tf.abs(0.01*weights))

def my_positive_weights(weights):
    return tf.where(weights<0, tf.zeros_like(weights), weights)

layer = keras.layers.Dense(30, activation=my_softplus, kernel_initializer=my_glorot_initializer, 
                           kernel_regularizer=my_l1_regularizer, kernel_constraint=my_positive_weights)

If a function has some hyperparameters that need to be saved along with the model,
then you will want to subclass the appropriate class, such as keras.regulariz
ers.Regularizer, keras.constraints.Constraint, keras.initializers.Initial
izer or keras.layers.Layer (for any layer, including activation functions). For
example, much like we did for the custom loss

In [ ]:
# custom l1 regularizer class
class MyL1Regularizer(keras.regularizers.Regularizer):

    def __init__(self, factor):
        self.factor = factor
    
    def __call__(self, weights):
        return tf.reduce_sum(tf.abs(self.factor * weights))

    def get_config(self):
        return {"factor": self.factor}
        

Implement the call() method for losses, layers (including activation
functions) and models, or the \_\_call\_\_() method for regularizers, initializers
and constraints. For metrics, things are a bit different,

## Custom metrics
Losses and metrics are conceptually not the same thing: losses are used by Gradient
Descent to train a model, so they must be differentiable (at least where they are evaluated)
and their gradients should not be 0 everywhere. Plus, it’s okay if they are not
easily interpretable by humans (e.g. cross-entropy). In contrast, metrics are used to
evaluate a model, they must be more easily interpretable, a

in most cases, defining a custom metric function is exactly the same as
defining a custom loss function. In fact, we could even use the Huber loss function we
created earlier as a metric6, it would work just fine (and persistence would also work
the same way, in this case only saving the name of the function, "huber_fn"):


In [ ]:
model.compile(loss="mse", optimizer="nadam", metrics=[create_huber(2.0)])


For each batch during training, Keras will compute this metric and keep track mean since the beginning of the epoch. Most of the time, this is exactly what you
want. But not always! Consider a binary classifier’s precision, for example. As we saw
in Chapter 3, precision is the number of true positives divided by the number of positive
predictions (including both true positives and false positives). Suppose the model
made 5 positive predictions in the first batch, 4 of which were correct: that’s 80% precision.
Then suppose the model made 3 positive predictions in the second batch, but
they were all incorrect: that’s 0% precision for the second batch. If you just compute
the mean of these two precisions, you get 40%. But wait a second, this is not the model’s
precision over these two batches! Indeed, there were a total of 4 true positives (4 +
0) out of 8 positive predictions (5 + 3), so the overall precision is 50%, not 40%. What
we need is an object that can keep track of the number of true positives and the numbur of false positives, and compute their ratio when requested. This is precisely what
the keras.metrics.Precision class does:

In [13]:
precision = keras.metrics.Precision()
precision([0, 1, 1, 1, 0, 1, 0, 1], [1, 1, 0, 1, 0, 1, 0, 1])

<tf.Tensor: shape=(), dtype=float32, numpy=0.8>

In [14]:
precision([0, 1, 0, 0, 1, 0, 1, 1], [1, 0, 1, 1, 0, 0, 0, 0])


<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [15]:
precision.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [16]:
precision.variables

[<tf.Variable 'true_positives:0' shape=(1,) dtype=float32, numpy=array([4.], dtype=float32)>,
 <tf.Variable 'false_positives:0' shape=(1,) dtype=float32, numpy=array([4.], dtype=float32)>]

In [18]:
precision.true_positives, precision.false_positives

(<tf.Variable 'true_positives:0' shape=(1,) dtype=float32, numpy=array([4.], dtype=float32)>,
 <tf.Variable 'false_positives:0' shape=(1,) dtype=float32, numpy=array([4.], dtype=float32)>)

In [19]:
precision.reset_states()

In [20]:
precision.variables, precision.result()

([<tf.Variable 'true_positives:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>,
  <tf.Variable 'false_positives:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>],
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0>)